# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

workspace 'MyNotesWorkspace.xcworkspace'
xcodeproj 'PersistenceLayer/PersistenceLayer.xcodeproj'

target 'PersistenceLayer' do

	pod 'AFNetworking', '~> 3.0.4'
	
end
