# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MyNotes' do
	pod 'MBProgressHUD', '~> 0.9.2'
	pod 'AFNetworking', '~> 3.0.4'
end
