# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MyNotes' do
	pod 'MBProgressHUD', '~> 0.9.2'
	pod 'Alamofire', '~> 3.1.5'
end

